name: Build and Release

on:
  push:
    tags:
      - "v*"

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Details
        id: details
        run: |
          version=$(awk '/^v[0-9]/ { print $1; exit }' CHANGELOG.md)
          echo "version=${version}" >> $GITHUB_ENV
          grep -zPo -e "(?s)${version}.*?\n-*?\n\n.*?\n\n" CHANGELOG.md | tail -n +3 >> .release_notes

      - name: Create Zipfile
        run: |
          zip -r ArmatureReset-${{ env.version }}.zip * -x ArmatureReset-${{ env.version }}.unitypackage -x Makefile

      - name: Setup Package
        run: |
          TARGET=Assets/SophieBlue/ArmatureReset
          mkdir -p $TARGET
          ls | grep -ve "\(Assets\|zip\)" | xargs -i{} mv {} $TARGET
          .github/workflows/generate_meta.sh bc846a2331c27846b961e0f9fe107d54 > Assets/SophieBlue.meta
          .github/workflows/generate_meta.sh e28b2d1d1cf6db59685e9d9ffc843e2f > Assets/SophieBlue/ArmatureReset.meta
          find Assets -type f -name \*.meta >> metaList

      - name: Create Unity Package
        uses: pCYSl5EDgo/create-unitypackage@master
        with:
          package-path: 'ArmatureReset-${{ env.version }}.unitypackage'
          include-files: metaList

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: "ArmatureReset ${{ env.version }}"
          body_path: .release_notes
          files: |
            ArmatureReset-${{ env.version }}.unitypackage
            ArmatureReset-${{ env.version }}.zip
